travis:
  secure:
    BINSTAR_TOKEN: wjDWvW1BPDIzuGNQBCrF8f9ZE6kHzbg7TOJvuTXpZp7QX+zNVwD8CJB+gms5dRt1ZvKLmm7LcbXK4zGRz5lsSTnAD1AfrJq8QquV3VFjkrkqxKBRQjAM3OvySG/mHqGyWwRrMrUOZD9tgwLs4mgQ+wPnJba+j7l58lxM25J9QEPrYcf61MGXXLJ+GuWmhT1ca6AjvKRwp8Wbx9TRMvsU1VZZfMF+kMJCfe9uENTMO0aWZkNAUfFRgLQ8ZIqn5uc86WBRc5c1KIYstp5HTWZo1CcsTSJU+ExSTu+UqmqR2TNlm2lp8PaO4bLVEYsP2iBvTz58cejdyB0QXtFiU6RlJw3AzpnGX8DVfRy91RP7x111oLtq9FkcClerIPllZqroOhm9pO9DN+8XrjyglMh6wGGnVCPImGzxts3adphiyCmlv4Rvgu1OTI4Swqf92D7aS7u0uLC3DJIxsQBL5LSqLGGyAXHfNLPCLflTnPvqRVmOeMrIx6tytTGrGlLsxDpfn3m5wgkJiU5gt5DvjS7LW6XdChJYNOlaPsgtColrkdGZOEWNTA6UtskXRiBnaTsOod4YA6st6kqU0ELWI69HWSqa17A7UGpE1RXZcXX1HrLHEMmJEoffIOzcBJ1sGWXrVLBxm+5/mceopiuynjUAK5QGfluIWHPnzEtcnAHHtxo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
